# Configuration for Alacritty, the GPU enhanced terminal emulator.

# GENERAL
# This section documents the [general] table of the configuration file.
[general]

# import = ["<string>",]
#
#   Import additional configuration files.
#   
#   Imports are loaded in order, skipping all missing files, with the 
#   importing file being loaded last. If a field is already present in a 
#   previous import, it will be replaced.
#   
#   All imports must either be absolute paths starting with /, paths 
#   relative to the user's home directory starting with ~/, or paths 
#   relative from the current config file.
#   
#   Example:
#   
#   import = [
#     "~/.config/alacritty/base16-dark.toml",
#     "~/.config/alacritty/keybindings.toml",
#     "alacritty-theme/themes/gruvbox_dark.toml",
#   ]

import = [
    "~/.config/alacritty/window.toml",
    "~/.config/alacritty/keyboard.toml",
    "~/.config/alacritty/font.toml",
]

# live_config_reload = true | false
#
#   Live config reload (changes require restart)
#    
#   Default: true

live_config_reload = true


# TERMINAL
# This section documents the [terminal] table of the configuration file.
[terminal]

# shell = "<string>" | { program = "<string>", args = ["<string>",] }
# 
# You can set shell.program to the path of your favorite shell, e.g. 
# /bin/zsh. Entries in shell.args are passed as arguments to the shell.
# 
# Default:
# 
#   Linux/BSD/macOS: $SHELL or the user's login shell, if $SHELL 
#   is unset
#   Windows: "powershell"
# 
# Example:
# 
#   shell = { program = "/bin/zsh", args = ["-l"] }

shell = { program = "/bin/zsh", args = ["-l"]}

# ENV
# All key-value pairs in the [env] section will be added as environment 
# variables for any process spawned by Alacritty, including its shell. Some entries 
# may override variables set by alacritty itself.
#
# Example:
# 
#   [env]
#   WINIT_X11_SCALE_FACTOR = "1.0"
[env]

TERM = "xterm-256color"