# FONT
#
# This section documents the [font] table of the configuration file.

# Default:
#
#   Linux/BSD: { family = "monospace", style = "Regular" }
#   Windows: { family = "Consolas", style = "Regular" }
#   macOS: { family = "Menlo", style = "Regular" }
# normal = { family = "<string>", style = "<string>" }
[font]
normal = { family = "BitstromWera Nerd Font", style = "Regular" }

# If the family is not specified, it will fall back to the value 
# specified for the normal font.
#
# Default: { style = "Bold" }
#
# bold = { family = "<string>", style = "<string>" }
bold = { style = "Bold" }

# If the family is not specified, it will fall back to the value 
# specified for the normal font.
#
# Default: { style = "Italic" }
#
# italic = { family = "<string>", style = "<string>" }
italic = { style = "Italic" }

# If the family is not specified, it will fall back to the value 
# specified for the normal font.
#
# Default: { style = "Bold Italic" }
#
# bold_italic = { family = "<string>", style = "<string>" }
bold_italic = { style = "Bold Italic" }

# Font size in points.
# 
# Default: 11.25
#
# size = <float>
size = 11.0

# Offset is the extra space around each character. y can be thought of 
# as modifying the line spacing, and x as modifying the letter spacing.
# 
# Default: { x = 0, y = 0 }
#
# offset = { x = <integer>, y = <integer> } 
offset = { x = 0, y = 0 }

# Glyph offset determines the locations of the glyphs within their cells 
# with the default being at the bottom. Increasing x moves the glyph to 
# the right, increasing y moves the glyph upward.
#
# glyph_offset = { x = <integer>, y = <integer> }
glyph_offset = { x = 0, y = 0 }

# When true, Alacritty will use a custom built-in font for box drawing 
# characters (Unicode points U+2500 - U+259F) and powerline symbols 
# (Unicode points U+E0B0 - U+E0B3).
#
# Default: true
#
# builtin_box_drawing = true | false
builtin_box_drawing = true