# WINDOW

# This section documents the [window] table of the configuration file.

# Window dimensions (changes require restart).
#
# Number of lines/columns (not pixels) in the terminal. Both lines and 
# columns must be non-zero for this to take effect. The number of 
# columns must be at least 2, while using a value of 0 for columns and 
# lines will fall back to the window manager's recommended size
#
# Default: { columns = 0, lines = 0 }
#
# dimensions = { columns = <integer>, lines = <integer> }
[window]
dimensions = { columns = 260, lines = 70 }

# Window startup position.
#
# Specified in number of pixels.
# If the position is "None", the window manager will handle placement.
# Default: "None"
#
# position = "None" | { x = <integer>, y = <integer> }
position = "None"

# Blank space added around the window in pixels. This padding is scaled 
# by DPI and the specified value is always added at both opposing sides.
# 
# Default: { x = 0, y = 0 }
#
# padding = { x = <integer>, y = <integer> }
padding = { x = 10, y = 10 }

# Spread additional padding evenly around the terminal content.
#
# Default: false
#
# dynamic_padding = true | false
dynamic_padding = true

# Window decorations.
# 
# Full
# 
#   Borders and title bar.
# 
# None
# 
#   Neither borders nor title bar.
# 
# Transparent (macOS only)
# 
#   Title bar, transparent background and title bar buttons.
# 
# Buttonless (macOS only)
# 
#   Title bar, transparent background and no title bar buttons.
#
# Default: "Full"
#
# decorations = "Full" | "None" | "Transparent" | "Buttonless"
decorations = "Buttonless"

# Background opacity as a floating point number from 0.0 to 1.0. The 
# value 0.0 is completely transparent and 1.0 is opaque.
# 
# Default: 1.0
#
# opacity = <float>
opacity = 0.70

# Request compositor to blur content behind transparent windows.
# 
# Default: false
# blur = true | false # (works on macOS/KDE Wayland)
blur = false

# Startup mode (changes require restart)
# 
# Windowed
# 
#   Regular window.
# 
# Maximized
# 
#   The window will be maximized on startup.
# 
# Fullscreen
# 
#   The window will be fullscreened on startup.
# 
# SimpleFullscreen (macOS only)
# 
#   Same as Fullscreen, but you can stack windows on top.
# 
# Default: "Windowed"
#
# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Windowed"

# Window title.
# 
# Default: "Alacritty"
#
# title = "<string>"
title = "Alacritty"

# Allow terminal applications to change Alacritty's window title.
#
# Default: true
#
# dynamic_title = true | false
dynamic_title = true

# Window class.
# 
# On Wayland, general is used as app_id and instance is ignored.
# 
# Default: { instance = "Alacritty", general = "Alacritty" }
#
# class = { instance = "<string>", general = "<string>" } # (Linux/BSD only)
class = { instance = "Alacritty", general = "Alacritty" }

# Override the variant of the System theme/GTK theme/Wayland client side 
# decorations. Set this to "None" to use the system's default theme 
# variant.
# 
# Default: "None"
#
# decorations_theme_variant = "Dark" | "Light" | "None"
decorations_theme_variant = "None"

# Prefer resizing window by discrete steps equal to cell dimensions.
# 
# Default: false
# 
# resize_increments = true | false
resize_increments = false

# Make Option key behave as Alt.
# 
# Default: "None"
# 
# option_as_alt = "OnlyLeft" | "OnlyRight" | "Both" | "None" # (macos only)
option_as_alt = "None"